DEBUG_MODE = False

FAKE_IMAGE_SIDE_PIXEL_COUNT = 2
MNIST_IMAGE_SIDE_PIXEL_COUNT = 28
FAKE_IMAGES_IN_DATASET_COUNT = 30
MNIST_IMAGES_CLASSES_COUNT = 10
FAKE_IMAGES_CLASSES_COUNT = 5

TEST_EXCLUDED_KEYS = []
TEST_EVAL_STEPS_INTERVAL = 2
TEST_TRAIN_STEPS = 3
TEST_BATCH_SIZE = 2

FAKE_EXPERIMENT_LAUNCHER_NAME = "fake-experiment"
STUB_LAUNCHER_RUNS_DIR_NAME = "STUB_LAUNCHER_RUNS_DIR_NAME"
TEST_IMAGE_SIZE = (5, 4, 3)
